quarkus.swagger-ui.path=/docs
quarkus.smallrye-openapi.jwt-security-scheme-value=bearer

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=fleet-flux
quarkus.datasource.password=fleet-flux-password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fleet-flux-java
# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.oidc.auth-server-url=http://localhost:8081/realms/fleet-flux-admin
quarkus.oidc.client-id=fleet-flux-admin-backend
quarkus.oidc.credentials.secret=KEYCLOAK_SECRET

quarkus.keycloak.admin-client.enabled=true
quarkus.keycloak.admin-client.server-url=http://localhost:8081
quarkus.keycloak.admin-client.realm=fleet-flux-admin
quarkus.keycloak.admin-client.client-id=fleet-flux-admin-master
quarkus.keycloak.admin-client.client-secret=KEYCLOAK_ADMIN_MASTER_SECRET
quarkus.keycloak.admin-client.grant-type=client_credentials

quarkus.super-admin.username=superadmin
quarkus.super-admin.email=superadmin@fleet-flux.com
quarkus.super-admin.password=superadmin
quarkus.super-admin.first-name=Super
quarkus.super-admin.last-name=Admin

