quarkus.swagger-ui.path=/docs
quarkus.smallrye-openapi.security-scheme=oauth2
quarkus.smallrye-openapi.jwt-security-scheme-value=bearer

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=fleet-flux
quarkus.datasource.password=fleet-flux-password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fleet-flux-java
# drop and create the database at startup (use `update` to only update the schema)
#quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.schema-management.strategy=validate

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# TODO - remove this
quarkus.oidc.auth-server-url=http://localhost:8081/realms/fleet-flux-admin
quarkus.oidc.client-id=fleet-flux-admin-backend
quarkus.oidc.credentials.secret=KEYCLOAK_SECRET

quarkus.keycloak.admin-client.enabled=true
quarkus.keycloak.admin-client.server-url=http://localhost:8081
quarkus.keycloak.admin-client.realm=master
quarkus.keycloak.admin-client.client-id=master-admin
quarkus.keycloak.admin-client.client-secret=KEYCLOAK_MASTER_ADMIN_SECRET
quarkus.keycloak.admin-client.grant-type=password
quarkus.keycloak.default-web-client-name=web

%test.quarkus.keycloak.admin-client.enabled=false
quarkus.http.test-port=8085

quarkus.keycloak.smpt-server.host=mailpit
quarkus.keycloak.smpt-server.port=1025
quarkus.keycloak.smpt-server.from=no-reply@fleet-flux.com
quarkus.keycloak.smpt-server.auth=false
quarkus.keycloak.smpt-server.starttls=false

quarkus.super-admin.realm=fleet-flux-admin
quarkus.super-admin.hostname=admin
quarkus.super-admin.username=superadmin
quarkus.super-admin.email=superadmin@fleet-flux.com
quarkus.super-admin.password=superadmin
quarkus.super-admin.first-name=Super
quarkus.super-admin.last-name=Admin


quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,PUT,POST,PATCH,DELETE

quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H 
#quarkus.http.cors.access-control-allow-credentials=true

#quarkus.log.category."io.quarkus.arc.processor".level=DEBUG
#quarkus.log.category."io.quarkus.arc".level=DEBUG
