#quarkus.smallrye-openapi.path=/docs
quarkus.swagger-ui.path=/docs

quarkus.oidc.auth-server-url=http://localhost:8081/realms/fleet-flux-admin
quarkus.oidc.client-id=fleet-flux-admin-backend
quarkus.oidc.credentials.secret=KEYCLOAK_SECRET