CREATE TABLE organization (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone NULL,
    updated_at timestamp(6) with time zone NULL,
    name character varying(255) NOT NULL,
    realm character varying(255) NOT NULL,
    slug character varying(255) NOT NULL
);

CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone NULL,
    updated_at timestamp(6) with time zone NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    keycloak_id character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    organization_id bigint NULL,

    CONSTRAINT app_user_organization_fk
        FOREIGN KEY (organization_id)
        REFERENCES organization(id)
);

CREATE TABLE tracking_device (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone NULL,
    updated_at timestamp(6) with time zone NULL,
    serial_number character varying(255) NOT NULL,
    model character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    organization_id bigint NULL,

    CONSTRAINT tracking_device_organization_fk
        FOREIGN KEY (organization_id)
            REFERENCES organization(id)
);

CREATE TABLE vehicle_brand (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone NULL,
    updated_at timestamp(6) with time zone NULL,
    name character varying(255) NOT NULL
);

CREATE TABLE vehicle (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,

    vehicle_brand_id bigint,
    organization_id bigint,

    variant varchar(180),
    model varchar(180),
    plate_number varchar(20),
    vin varchar(30),
    year_of_manufacture integer,

    category varchar(255),
    status varchar(255),
    type varchar(255),
    fuel_type varchar(255),

    fuel_capacity_in_liters double precision,
    avg_consumption_per100km double precision,

    last_service_date timestamp(6) with time zone,

    insurance_policy_number varchar(40),
    insurance_expiry_date timestamp(6) with time zone,
    insurance_company varchar(180),

    inspection_due_date timestamp(6) with time zone,

    ownership_type varchar(255),

    CONSTRAINT vehicle_vehicle_brand_fk
        FOREIGN KEY (vehicle_brand_id)
            REFERENCES vehicle_brand (id),

    CONSTRAINT vehicle_organization_fk
        FOREIGN KEY (organization_id)
            REFERENCES organization (id)
);