CREATE TABLE vehicle_driver_assignment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,

    vehicle_id bigint,
    driver_id bigint,
    start_date timestamp(6) with time zone NOT NULL,
    end_date timestamp(6) with time zone,

    assigned_by bigint NOT NULL,

    notes varchar(3000),

    CONSTRAINT vehicle_driver_assignment_vehicle_fk
        FOREIGN KEY (vehicle_id)
            REFERENCES vehicle (id),

    CONSTRAINT vehicle_driver_assignment_driver_fk
        FOREIGN KEY (driver_id)
            REFERENCES app_user (id),

    CONSTRAINT vehicle_driver_assignment_assigned_by_fk
        FOREIGN KEY (assigned_by)
            REFERENCES app_user (id)
);